# Generated by Django 4.1.9 on 2023-07-20 14:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 20, 14, 1, 9, 579602, tzinfo=datetime.timezone.utc))),
                ('difficulty', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Extreme', 'Extreme')], max_length=20)),
                ('bpm', models.IntegerField(blank=True, null=True)),
                ('song_original', models.FileField(default=None, upload_to='songs/original')),
                ('song_pdf', models.FileField(blank=True, default=None, null=True, upload_to='songs/pdf')),
                ('song_musescore', models.FileField(blank=True, default=None, null=True, upload_to='songs/musescore')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
