# Generated by Django 4.1.9 on 2023-05-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_song_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='filepath',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
