# Generated by Django 4.1.9 on 2023-06-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_song_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_base64',
            field=models.FileField(default='hello default', upload_to='blobs'),
            preserve_default=False,
        ),
    ]
