# Generated by Django 4.1.9 on 2023-07-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_alter_song_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
