# Generated by Django 4.1.9 on 2023-07-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_song_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
