# Generated by Django 4.1.9 on 2023-06-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0011_song_bpm_song_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='filepath',
            new_name='filepath_original',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_base64',
        ),
        migrations.AddField(
            model_name='song',
            name='song_musescore',
            field=models.FileField(blank=True, default=None, null=True, upload_to='songs/musescore'),
        ),
        migrations.AddField(
            model_name='song',
            name='song_original',
            field=models.FileField(default=None, upload_to='songs/original'),
        ),
        migrations.AddField(
            model_name='song',
            name='song_pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to='songs/pdf'),
        ),
    ]
