# Generated by Django 4.1.9 on 2023-06-27 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0012_rename_filepath_song_filepath_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 27, 16, 39, 16, 887314, tzinfo=datetime.timezone.utc)),
        ),
    ]
