# Generated by Django 4.1.9 on 2023-06-28 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0015_alter_song_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 28, 2, 42, 20, 839761, tzinfo=datetime.timezone.utc)),
        ),
    ]
