# Generated by Django 4.1.9 on 2023-06-28 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0017_alter_song_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 28, 5, 49, 48, 467127, tzinfo=datetime.timezone.utc)),
        ),
    ]
