# Generated by Django 4.1.9 on 2023-06-28 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0018_alter_song_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 28, 6, 53, 37, 741611, tzinfo=datetime.timezone.utc)),
        ),
    ]
