# Generated by Django 4.1.9 on 2023-07-12 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0045_alter_song_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='download_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 12, 16, 7, 20, 851807, tzinfo=datetime.timezone.utc)),
        ),
    ]
