# Generated by Django 4.1.9 on 2023-07-12 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0046_song_download_link_alter_song_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='download_link',
        ),
        migrations.RemoveField(
            model_name='song',
            name='filepath_original',
        ),
        migrations.AlterField(
            model_name='song',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 12, 16, 28, 40, 943116, tzinfo=datetime.timezone.utc)),
        ),
    ]
